-- Tablas para modulo de prestamos
CREATE TABLE IF NOT EXISTS `loans` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(180) NOT NULL,
  `document_id` VARCHAR(80) NOT NULL,
  `principal_amount` DECIMAL(14,2) NOT NULL,
  `cut_frequency` VARCHAR(20) NOT NULL,
  `term_cuts` INT UNSIGNED NOT NULL,
  `rate_per_cut` DECIMAL(8,4) NOT NULL,
  `per_cut_amount` DECIMAL(14,2) NOT NULL,
  `final_cut_amount` DECIMAL(14,2) NOT NULL,
  `total_gain` DECIMAL(14,2) NOT NULL,
  `total_to_collect` DECIMAL(14,2) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `created_by_user_id` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_loans_document_id` (`document_id`),
  KEY `idx_loans_status` (`status`),
  KEY `idx_loans_full_name` (`full_name`),
  KEY `idx_loans_created_by` (`created_by_user_id`),
  CONSTRAINT `fk_loans_users_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `loan_cuts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `loan_id` BIGINT UNSIGNED NOT NULL,
  `cut_number` INT UNSIGNED NOT NULL,
  `original_due_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `base_amount` DECIMAL(14,2) NOT NULL,
  `penalty_percent` DECIMAL(8,2) NOT NULL DEFAULT 0,
  `amount` DECIMAL(14,2) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `note` TEXT NULL,
  `proof_path` VARCHAR(500) NULL,
  `paid_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_loan_cuts_loan_cut_number` (`loan_id`, `cut_number`),
  KEY `idx_loan_cuts_loan_id` (`loan_id`),
  KEY `idx_loan_cuts_status` (`status`),
  KEY `idx_loan_cuts_due_date` (`due_date`),
  CONSTRAINT `fk_loan_cuts_loans` FOREIGN KEY (`loan_id`) REFERENCES `loans` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
